In [ ]:
from minitorch import MultiHeadAttention
import minitorch
from minitorch.cuda_kernel_ops import CudaKernelOps
import numpy as np
from minitorch.tensor import tensor, tensor_from_numpy
from minitorch.module import Module, Parameter
from minitorch.tensor_ops import *


In [17]:

backend = minitorch.TensorBackend(CudaKernelOps)

In [21]:
np_ones = np.ones((1,5,10))
np.random.seed(10)

np10x10_ones = np.random.normal(0,1,(10,10))
m=MultiHeadAttention(10, 2, True, 0.0, False, backend)  
m.q_projection.weights.value = tensor_from_numpy(np10x10_ones, backend, True)
m.k_projection.weights.value = tensor_from_numpy(np10x10_ones, backend, True)
m.v_projection.weights.value = tensor_from_numpy(np10x10_ones, backend, True)
m.out_projection.weights.value = tensor_from_numpy(np10x10_ones, backend, True)
x =  tensor_from_numpy(np_ones, backend, True)
y=m(x)
y.sum().backward()
m.v_projection.weights.value.grad


[
	[9.433045 2.734372 14.428965 -0.391024 -4.582525 15.132296 -2.703501 11.423223 -4.852634 -0.913881]
	[9.433045 2.734372 14.428965 -0.391024 -4.582525 15.132296 -2.703501 11.423223 -4.852634 -0.913881]
	[9.433045 2.734372 14.428965 -0.391024 -4.582525 15.132296 -2.703501 11.423223 -4.852634 -0.913881]
	[9.433045 2.734372 14.428965 -0.391024 -4.582525 15.132296 -2.703501 11.423223 -4.852634 -0.913881]
	[9.433045 2.734372 14.428965 -0.391024 -4.582525 15.132296 -2.703501 11.423223 -4.852634 -0.913881]
	[9.433045 2.734372 14.428965 -0.391024 -4.582525 15.132296 -2.703501 11.423223 -4.852634 -0.913881]
	[9.433045 2.734372 14.428965 -0.391024 -4.582525 15.132296 -2.703501 11.423223 -4.852634 -0.913881]
	[9.433045 2.734372 14.428965 -0.391024 -4.582525 15.132296 -2.703501 11.423223 -4.852634 -0.913881]
	[9.433045 2.734372 14.428965 -0.391024 -4.582525 15.132296 -2.703501 11.423223 -4.852634 -0.913881]
	[9.433045 2.734372 14.428965 -0.391024 -4.582525 15.132296 -2.703501 11.423223 -4.85263

In [ ]:
[
	[2.990415 8.881533 17.826761 4.652535 -8.729689 21.574926 -8.850663 8.025425 -9.896193 3.233282]
	[2.990415 8.881533 17.826761 4.652535 -8.729689 21.574926 -8.850663 8.025425 -9.896193 3.233282]
	[2.990415 8.881533 17.826761 4.652535 -8.729689 21.574926 -8.850663 8.025425 -9.896193 3.233282]
	[2.990415 8.881533 17.826761 4.652535 -8.729689 21.574926 -8.850663 8.025425 -9.896193 3.233282]
	[2.990415 8.881533 17.826761 4.652535 -8.729689 21.574926 -8.850663 8.025425 -9.896193 3.233282]
	[2.990415 8.881533 17.826761 4.652535 -8.729689 21.574926 -8.850663 8.025425 -9.896193 3.233282]
	[2.990415 8.881533 17.826761 4.652535 -8.729689 21.574926 -8.850663 8.025425 -9.896193 3.233282]
	[2.990415 8.881533 17.826761 4.652535 -8.729689 21.574926 -8.850663 8.025425 -9.896193 3.233282]
	[2.990415 8.881533 17.826761 4.652535 -8.729689 21.574926 -8.850663 8.025425 -9.896193 3.233282]
	[2.990415 8.881533 17.826761 4.652535 -8.729689 21.574926 -8.850663 8.025425 -9.896193 3.233282]]


[
	[0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000]
	[0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000]
	[0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000]
	[0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000]
	[0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000]
	[0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000]
	[0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000]
	[0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000]
	[0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000]
	[0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000]]

In [117]:
y=m(x)

In [4]:
y


[
	[
		[5.369593 0.966324 -12.508625 8.166962 10.864056 6.004936 -0.250119 6.299362 9.412932 -12.980747]
		[6.939350 8.842599 10.219313 -11.155605 -7.147309 -4.056501 6.718268 -5.945041 -15.139590 -5.890635]
		[8.036162 2.119884 -16.379766 10.296718 14.379575 7.938686 0.250354 8.178030 11.665155 -18.461407]
		[7.121964 4.463542 -5.535398 1.735536 5.531856 3.013258 2.618706 2.453023 1.044110 -12.656148]
		[-20.834011 -16.966730 2.609337 6.099866 -5.274689 -2.731110 -11.285677 0.075905 11.002531 31.419449]]]

In [79]:
x_numpy = np.random.normal(0,1,(2, 4, 5))
w_numpy = np.random.normal(0,1,(2, 5, 4))
x = tensor_from_numpy(x_numpy, TensorBackend(SimpleOps),True)   # pretend B=2, H=3
w = tensor_from_numpy(w_numpy, TensorBackend(SimpleOps),True)
y = (x @ w).sum()
y.backward()
print(x.grad.sum())  # should be non‑zero
print(w.grad.sum())  # "

NameError: name 'TensorBackend' is not defined

In [67]:
grad_x_auto = x.grad.to_numpy().copy()
grad_w_auto = w.grad.to_numpy().copy()

In [74]:
import numpy as np

eps = 1e-4
grad_x_fd = np.zeros_like(grad_x_auto)
grad_w_fd = np.zeros_like(grad_w_auto)

# --- gradient w.r.t x ----------------------------------------
it = np.nditer(x.to_numpy(), flags=['multi_index'])
while not it.finished:
    idx = it.multi_index
    
    plus  = x.to_numpy().copy(); plus[idx]  += eps
    minus = x.to_numpy().copy(); minus[idx] -= eps
    
    y_plus  = (tensor_from_numpy(plus,  backend) @ w).sum().item()
    y_minus = (tensor_from_numpy(minus, backend) @ w).sum().item()
    
    grad_x_fd[idx] = (y_plus - y_minus) / (2 * eps)
    it.iternext()

# --- gradient w.r.t w ----------------------------------------
it = np.nditer(w.to_numpy(), flags=['multi_index'])
while not it.finished:
    idx = it.multi_index
    
    plus  = w.to_numpy().copy(); plus[idx]  += eps
    minus = w.to_numpy().copy(); minus[idx] -= eps
    
    y_plus  = (x @ tensor_from_numpy(plus,  backend)).sum().item()
    y_minus = (x @ tensor_from_numpy(minus, backend)).sum().item()
    
    grad_w_fd[idx] = (y_plus - y_minus) / (2 * eps)
    it.iternext()

In [75]:
abs_err_x = np.abs(grad_x_auto - grad_x_fd).max()
abs_err_w = np.abs(grad_w_auto - grad_w_fd).max()


In [76]:
print("max abs‑error (x):", abs_err_x)
print("max abs‑error (w):", abs_err_w)

max abs‑error (x): 0.01023984
max abs‑error (w): 0.0103263855


In [3]:
import numpy as np
np.arange(0,10).reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])